[package]
name = "dtim"
version = "0.1.0"
edition = "2021"
default-run = "dtim"

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
uuid = {version = "1.16", features = ["v7", "serde"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"