[default]
address = "0.0.0.0"
port = 3030
log_level = "info"

[default.tls]
key_rotation_days = 7
ca = "certs/ca.crt"
certs = "certs/node.crt"
key = "certs/node.key"

[default.storage]
encrypted_logs_path = "data/logs"

[default.network]
gossip_interval_seconds = 60
peers_per_round = 3
registry_url = "https://registry.dtim.example.com"

[[default.network.init_peers]]
id = "2"
endpoint = "https://peer1.example.com:3030"
public_key = "Mg=="

[[default.network.init_peers]]
id = "3"
endpoint = "https://peer2.example.com:3030"
public_key = "Mw=="

[default.privacy]
level = "moderate"         # Options: "strict", "moderate", "open"
allow_custom_fields = true

[default.watchers]
ufw_log_path = "/var/log/ufw.log"
fail2ban_log_path = "/var/log/fail2ban.log"
suricata_log_path = "/var/log/suricata/eve.json"
zeek_log_dir = "/opt/zeek/logs/current"
clamav_scan_dir = "/var/tmp/scan"
nginx_access_log = "/var/log/nginx/access.log"
nginx_error_log = "/var/log/nginx/error.log"
apache_access_log = "/var/log/apache2/access.log"
apache_error_log = "/var/log/apache2/error.log"
